= Curriculum Vitae
Luis Oscar
2016-03-23
:jbake-type: page
:jbake-status: published


== Company CarTrawler / Integration Specialist
From May 2015 to Present

=== Projects
* otaserver
* otarobot

=== Description
* I am a team player always ready to help everyone, helping to form a high performance award-winning team in a rapidly growing organization.
* Currently support to core business software components, develop and extend new features following established guidelines.
* I interface with suppliers and partners all over the globe on a technical level, and support our system users.
* I solve issues in production and implementing new business features.
* I identified and implemented practical solutions to old problems and taken ownership, namely of:
 ** Tracking network IO problems in the supply chain
 ** Managing and pruning locations data.
 ** Automate the reporting of system wide configuration

=== Technologies
Java/Tomcat, Ant & Gradle, Git & SVN, SOAP, http://www.service-architecture.com/articles/xml/opentravel_alliance_ota.html[Open Travel Alliance Message Exchange Protocol(OTA)],MS-SQL


== Company 123.ie / Senior Java Developer
From May 2014 to May 2015.

Part of high performance team in a leading award-winning 24x7x365 online business, doing full stack development frontend, backend services layer, and database.

=== Projects

* WebRebrand
* Peril Based Quote Engine
* Devops/Operational Support

=== Description
* Devops, support troubleshooting productions issues, with 1-2 days SLA's.
* Implemented the new web site re-brand, with responsive single page apps, cross-browser compatibility support, end user analytics, and live chat.
* Implemented quick prototypes and prove of concepts using Groovy.
* Evolved core business components with sizable code base, integration of new 3rd party service providers into the business fabric.
* Worked with Agile/Scrum, continuous delivery, test automation using behavior driven development.
* Present ideas and proposed solutions to business needs, created prototype to index quote metadata using ElasticSearch.

=== Technologies

JBoss/JEE, CFX, Drools, Spring, Groovy, Jenkins, AngularJS, SVN, SoapUI, Jira, Linux


== Company PADDY POWER / Senior Software Engineer
From October 2013 to April 2014.
Part of leading Irish bookmaker, practitioner of the best agile software development practices and continues deployment.

=== Projects
* SingleWallet
* FraudDasboard

=== Description
* Develop next generation payment methods and web services, and strategic business solutions.
* Experience securing financial transactions using cryptography; RSA asymmetric-keys, Triple DES symmetric-key, integration with OEM’s, and exposure to security awareness in business applications.
* Developed authentication and authorization of corporate users, using “Spring Security” backed by Microsoft´s Active Directory LDAP protocol.
* Usage of distributed version control system Git enhanced by GitLabs and Atlassian Stash.
* Experience working with continuous delivery backed by Jenkins and the pipeline plugin, having environments provisioned on the fly in Cloud Foundry as part of the build process.
* On the process front learn to value Agile and “Kanban” with Specification by example, and collaborative team input as means to deliver end product quality and end user satisfaction.
* Experience applying Behavior Drive Development namely using “Thucydides”.

=== Technologies
Java/Tomcat Spring, Spring Web Services, Spring MVC, Spring Security, Java Cryptography Architecture, Jenkins, Git, LDAP Active Directory, SoapUI, Thucydides/Jbehave, Splunk


== Company Dun & Bradstreet  / Java Developer
From Oct 2011 to Oct 203.

=== Projects
* US Bankruptcy
* DnbDataHub
* DNBi
* MyDnb
* DnbiPro


=== Description
* Analysis and reengineering of US Bankruptcy business process.
* Developed quick Product POC's, using AngularJS, Gradle, Spring Security, and Apache Camel.
* Working with international teams: India, US, Ireland
* Provided ongoing support bug fixing for company products.
* Developed test automation framework, using WebDriver, Spring, and PageObjects Pattern
* Setup of developers environment, Linux system operation, Build Automation using Gradle
* Supporting roll-out new software components into company products, Actuate BIRT iServer
* Presenting tech talk to pears, fostering new technologies into the group; Camel, Gradle . 
* Training: Advance presentation skills, Actuate BIRT reports development
* Experience using Mercurial version control system.
* Provided ongoing support maintenance for company flagship product DNBi, https://sso.dnbi.com/cas/login


=== Technologies
Java/JBoss/Tomcat/Jetty, Spring, Spring MVC,Apache Camel, Jenkins, Mercurial, SVN, Maven, Gradle, BIRT, Selenium,  Webdriver, Cucumber BDD, PhantomJS,AngularJS, JQuery, HMTL, CSS


== Accenture & EdgeInnovation / Senior Java Consultant
From Aug 2010 to Oct 2011.
Senior Consultant with Accenture at Zon, leading Portuguese telecom provider with 3 million customer base, and hundreds of products for sale in product catalog.
UFE is a key project to both Accenture and Zon, with many innovations, targeted to become the gateway to all IT systems, and provide for customer self-care.
As web frontend it is been used by call center, customer stores and technical support, it is expected to have 2k users.

=== Projects
* Unified Front End (UFE)

=== Description

* Setup the project base framework and integrated core software components, and staff training.
* Developed business rules server for customer portfolio validation.
* Developed ETL to convert from Siebel business rules to Drools (parser & code generator).
* Developed Batch processing feature for execution of scheduled tasks.
* Developed Test regression framework for business rules validation.
* Developed Templated document printing framework.

=== Technologies
Jboss Drools, Jboss Jbpm,  Apache Camel, Spring Framework, Spring Batch Processing, Spring Security, Maven,  SpringSource STS, SVN, JSF/Icefaces


== Company GTInformatica / Senior Developer
From Oct. 2007 to  Oct. 2010.

=== Projects

|===
|Project | Description

|GT GuiaReporting, QEnergia, May. 2010
|Extend previously developed solution for QEnergia, with reporting and analytical features.
 Added web interface to query and view existing data about industrial automated concrete production system, allowing customer to gather metrics about the production process.
 Featured, rich and interactive search interface with AJAX autocomplete and Hibernate Search integration.
 Technologies: https://grails.org[Grails],
               http://www.h2database.com/html/main.html[H2 Database],
               http://www.eclipse.org/birt/[BIRT],
               https://jquery.com[jQuery],
               https://spring.io/tools[SpringSource STS],
               https://subversion.apache.org[SVN]

|GT/NetPlus, Feb. 2010 - Mar. 2010
|GT Informática, Senior Analyst Developer
 Development of business intelligence reporting solution for Ethernet network.
 Did requirements gathering, project documentation, programing, interfacing with networking experts, training junior developers.
 Technologies: Spring, MySQL, BIRT,Hibernate, Log4j, SpringSource STS, SVN, Maven

|Outsourcing GT/ Promosoft, Nov. 2009 - Dec. 2009
|Outsourcing GT Informática, Senior Analyst Developer
 Development of communications module for banking solution.
 Started from conceptual documentation for reengineering of the communications module towards performance improvements of the overall solution.
 My assignments where: development, team coordination, alignment with project goals, reporting progress, writing technical documentation.
 The communication module integrates IBM/AS400 with a modern web based interface core to the business.
 Technologies: IBM WebSphere, JTOpen, Spring, H2 Database,Hibernate, Log4j, SpringSource STS, SVN, Maven, Hudson

|Outsourcing GT / Vigilarme, Oct. 2009
|Outsourcing GT Informática, Senior Analyst Developer
 Development of integration between Lenel OnGuard security solution and NSC Solution F1 fire alarm device panel from SECTRON.
 Additionally did customer interface, mentoring junior developer, and writing of technical documentation for product certification by OEM providers, towards deployment at Beja Airport.
 Technologies: VB.NET, Spring .NET, Log4Net, C++, Visual Studio, SVN, Wireshark

| OutSourcing GT/ RedCats LaRedoute, May 2008 – June 2009
| GT Informática Outsourcing, Senior Analyst Developer
  The customer business is catalog sale, and I provided value add service by extending their innovation.
  Did bug-fixing and extended the existing product with new features, i.e: Ajax, Integration with Payment Service Provider.
  Provided couching of customer personal to work on the project and did mentoring of junior developers.
  The product was core to the customer business and was made available in 9 different languages, the project consisted mainly of migrating old IBM/AS400 applications.
  Technologies: IBM Rational Software Development Platform, Java/J2EE/JSF, HTML, Javascript/JQuery/DWR, SVN

|GT Autómato, QEnergia Dec. 2008
|QEnergia is a engineering firm providing solutions in industrial automation.
 Extended the customer existing product, add printable invoices feature to automated production of concrete solution.
 Interfaced with the Saia-Burgess PCD controller, using HTTP and FTP, extracted data from the controller and outputted printable PDF invoices.
 Technologies: Java, Java Service Wrapper, Jakarta Commons Net,iText,Apache POI, Spring Framework, IzPack, Groovy, OpenOffice

|Billing REFER-TELECOM Oct.  2007 – May. 2008
|Provided support to billing processing for medium size telecom provider.
 Performed all the tasks required to produce customer monthly invoices, collected billing records from hardware, performed configuration of billing platform, and ongoing technical support.
 Technologies: SQL SERVER, .NET

|===


== Company Vallent IBM Ireland / Java developer
From Jun. 2006 to Set. 2007.

=== Projects
* R&D and Professional Services


=== Description
* Provided support and bug fix for the ServiceAssure.
* Design and implementation of the application Diagnostics & Troubleshooting feature.
* Develop VBA Add-In for Business Objects report filter.
* Develop Excel VBA for excel spreadsheet validation
* Develop ETL utility, using POI for network provisioning.
* Testing system components for customer acceptance test.

=== Technologies
Sun Solaries, Oracle, ChangeSynergy, JSE, VBA


== Company Qumas Ireland / Java developer
From Nov. 2004 to Jun. 2006.

=== Projects
* QProcessCompliance

=== Description
* Provided support and bug fixing for QProcessCompliance.
* Design and implementation of the application business rule engine based on AOP and Drools.
* Training and mentoring of junior developers.
* Setting up an automated build system using Luntbuild and Maven.

=== Technologies
Maven, Tomcat, Spring Framework, Drools,Oracle, JUNIT, Log4j, PVCS, Perforce

== Company Siemens Portugal
From Dec. 2000 to Nov. 2004.

=== Projects

|===
|Project | Description

|ETHERNET MANAGER R&D WON (Wired and Optical Networks). Lisbon, Nov. 2003 to Nov. 2004
|This project consists of a Multi-tier network management solution for Ethernet Carrier Grade networks based on J2SE/J2EE.
 The project is composed of 4 teams; System Engineer, Server, Client and Integration, each team has one team leader and there is one project manager, this sum up to a total of 40 people.
 Acting as a developer in the Server team I took part on the following activities:
 Creation of team knowledge base WEB site based on PHPWIKI.
 Elaboration of the project test strategy documentation providing recommendations o; TDD, Mock Objects, Logical UNIT, INTEGRATION UNIT, Functional UNIT, Automate GUI testing.
 Evaluation of project technology paths; AspectJ for Logging and Tracing, AndroMDA for prototyping.
 Elaboration of project requirements and design spec documentation.
 Mentoring junior developers.
 Preparation and attendance of Q&A session with Christian Bauer from Hibernate.
 Development and test environment setup.
 Technologies: JBoss, JMS, EJB, XDoclet, Hibernate, HSQL, JUNIT, Log4j , PHPWIK, DbUnit, Cruise Control, EasyMock, Maven

|VODAFONE MS&D Platform  Lisbon, Ago. – Oct. 2003
|I took part of the system integration team in the project bring up for VODAFONE/PT.
 The team was composed of 10 people, mostly of Unix experts, Oracle DBA’s, and TCP/IP network administrators.
 Acting as developer that took part in the project development phase I provided support for the system integration team and performed installation and management of Helix video Streaming Server, Weblogic.
 Technologies: Helix RealServer,  Weblogic

 |VODAFONE MS&D Platform  Munich Apr. – Jul. 2003
 |From the technical point of view this was J2SE/JMS/JMX application deployed on a Solaris Cluster.
  The team was composed of 10 people from several nationalities, 2 team leaders, one PM, and one System Engineer.
  As a developer my role was development of interfaces to VODAFONE/PT billing system.
  Technologies: Weblogic, JMS, Torque, JUNIT, Log4j

|ICM/WM TC45 Berlin, Jan. – Apr.  2003
|Testing J2ME networking API implementation of Siemens TC45 Wireless Module.
 I was integrated in the Siemens Berlin TC45 development, which was composed of 6 Hardware/Software Engineers, and one PM.
 My job was to develop a Sample application the “Intelligent House” using the J2ME API and Siemens TC45 API. The goal was to perform IO on incoming events such as SMS or TCP/IP connections.
 Technologies: J2ME, TC45 SDK

|Docbec  Nov. – Dec. 2002
|Web based document management for the Quality Department. The team was composed 2 developers, one junior and one team leader. As a developer I took part in the following activates:
* Requirements evaluation and afford estimation.
* Development of Mailing list facility based on JavaMail API and JDNI/LADP accessing Microsoft Exchange server.
* Development of PDF reporting facility based on XML/XSL FOP.
* Integration of Tomcat with Siemens Intranet web server, which is IIS.
* Technologies: IIS, Tomcat, Struts, Velocity, FOP,SQL Server, JDNI to access Exchange LADP, Castor, HSQL, Log4j

|Xanthus SMS Gateway 2002
|Web administration console for SMS Gateway. The gateway was based on Kannel open source SMS gateway and run on a Linux box.
 The team was composed of 2 developers, one junior and one team leader.
 As a developer I took part in the following activities:
 Analysis design and implementation.
 RPM installation package development.
 Technologies: Tomcat, Struts, Velocity, Log4j, JDBC, MySQL

|Mobile Office 2002
|Web Personal information management application
 For PDA and   WAP enabled mobile devices
 The team was composed of 2 developers, and one team leader.
 As a developer I took part in the following activities:
 - Analysis design and implementation.
 Technologies: Tomcat, Struts, Velocity, Log4j, Torque, MySQL

|Multimedia Messaging 2001
|Web Mail for PDA with multimedia capabilities
 The team was composed of 2 developers, and one team leader.
 As a developer I took part in the following activities:
 - Analysis design and implementation.
 Technologies: Apache, PHP, MySQL

|SOSMobile 2001
|WAP based interface for Mobile Phone Technical Assistance Department.
 The team was composed of 2 developers, and one team leader.
 As a developer I took part in the following activities:
 Analysis design and implementation based on the Cocoon framework that allowed me to produce WML suitable for several mobiles.
 Technologies: Tomcat, Cocoon, IIS, SQL Server

|SiePegasus/WapMail 2000
|Linux based WEB/WAP Mail solution.
 The team was composed of 2 developers, and one team leader.
 As a junior developer I did PHP scripting.
 Technologies: Apache, PHP, MySQL


|===

////
== Company XPTO / Position Y
From May 2014 to May 2015.

=== Projects
* P1
* P1


=== Description
* Did 1
* Did 2
* Did 3

=== Technologies
X, Y, Z
////
