= Curriculum Vitae
Luis Oscar
2016-03-23
:jbake-type: page
:jbake-status: published


== Company CarTrawler / Integration Specialist
From May 2015 to Present

=== Projects
* otaserver
* otarobot

=== Description
* I am a team player always ready to help everyone, helping to form a high performance award-winning team in a rapidly growing organization.
* Currently support to core business software components, develop and extend new features following established guidelines.
* I interface with suppliers and partners all over the globe on a technical level, and support our system users.
* I solve issues in production and implementing new business features.
* I identified and implemented practical solutions to old problems and taken ownership, namely of:
 ** Tracking network IO problems in the supply chain
 ** Managing and pruning locations data.
 ** Automate the reporting of system wide configuration

=== Technologies
Java/Tomcat, Ant & Gradle, Git & SVN, SOAP, Open Travel Alliance Message Exchange Protocol(OTA),MS-SQL


== Company 123.ie / Senior Java Developer
From May 2014 to May 2015.

Part of high performance team in a leading award-winning 24x7x365 online business, doing full stack development frontend, backend services layer, and database.

=== Projects

* WebRebrand
* Peril Based Quote Engine
* Devops/Operational Support

=== Description
* Devops, support troubleshooting productions issues, with 1-2 days SLA's.
* Implemented the new web site re-brand, with responsive single page apps, cross-browser compatibility support, end user analytics, and live chat.
* Implemented quick prototypes and prove of concepts using Groovy.
* Evolved core business components with sizable code base, integration of new 3rd party service providers into the business fabric.
* Worked with Agile/Scrum, continuous delivery, test automation using behavior driven development.
* Present ideas and proposed solutions to business needs, created prototype to index quote metadata using ElasticSearch.

=== Technologies

JBoss/JEE, CFX, Drools, Spring, Groovy, Jenkins, AngularJS, SVN, SoapUI, Jira, Linux


== Company PADDY POWER / Senior Software Engineer
From October 2013 to April 2014.
Part of leading Irish bookmaker, practitioner of the best agile software development practices and continues deployment.

=== Projects
* SingleWallet
* FraudDasboard

=== Description
* Develop next generation payment methods and web services, and strategic business solutions.
* Experience securing financial transactions using cryptography; RSA asymmetric-keys, Triple DES symmetric-key, integration with OEM’s, and exposure to security awareness in business applications.
* Developed authentication and authorization of corporate users, using “Spring Security” backed by Microsoft´s Active Directory LDAP protocol.
* Usage of distributed version control system Git enhanced by GitLabs and Atlassian Stash.
* Experience working with continuous delivery backed by Jenkins and the pipeline plugin, having environments provisioned on the fly in Cloud Foundry as part of the build process.
* On the process front learn to value Agile and “Kanban” with Specification by example, and collaborative team input as means to deliver end product quality and end user satisfaction.
* Experience applying Behavior Drive Development namely using “Thucydides”.

=== Technologies
Java/Tomcat Spring, Spring Web Services, Spring MVC, Spring Security, Java Cryptography Architecture, Jenkins, Git, LDAP Active Directory, SoapUI, Thucydides/Jbehave, Splunk


== Company Dun & Bradstreet  / Java Developer
From Oct 2011 to Oct 203.

=== Projects
* US Bankruptcy
* DnbDataHub
* DNBi
* MyDnb
* DnbiPro


=== Description
* Analysis and reengineering of US Bankruptcy business process.
* Developed quick Product POC's, using AngularJS, Gradle, Spring Security, and Apache Camel.
* Working with international teams: India, US, Ireland
* Provided ongoing support bug fixing for company products.
* Developed test automation framework, using WebDriver, Spring, and PageObjects Pattern
* Setup of developers environment, Linux system operation, Build Automation using Gradle
* Supporting roll-out new software components into company products, Actuate BIRT iServer
* Presenting tech talk to pears, fostering new technologies into the group; Camel, Gradle . 
* Training: Advance presentation skills, Actuate BIRT reports development
* Experience using Mercurial version control system.
* Provided ongoing support maintenance for company flagship product DNBi, https://sso.dnbi.com/cas/login


=== Technologies
Java/JBoss/Tomcat/Jetty, Spring, Spring MVC,Apache Camel, Jenkins, Mercurial, SVN, Maven, Gradle, BIRT, Selenium,  Webdriver, Cucumber BDD, PhantomJS,AngularJS, JQuery, HMTL, CSS


== Accenture & EdgeInnovation / Senior Java Consultant
From Aug 2010 to Oct 2011.
Senior Consultant with Accenture at Zon, leading Portuguese telecom provider with 3 million customer base, and hundreds of products for sale in product catalog.
UFE is a key project to both Accenture and Zon, with many innovations, targeted to become the gateway to all IT systems, and provide for customer self-care.
As web frontend it is been used by call center, customer stores and technical support, it is expected to have 2k users.

=== Projects
* Unified Front End (UFE)

=== Description

* Setup the project base framework and integrated core software components, and staff training.
* Developed business rules server for customer portfolio validation.
* Developed ETL to convert from Siebel business rules to Drools (parser & code generator).
* Developed Batch processing feature for execution of scheduled tasks.
* Developed Test regression framework for business rules validation.
* Developed Templated document printing framework.

=== Technologies
Jboss Drools, Jboss Jbpm,  Apache Camel, Spring Framework, Spring Batch Processing, Spring Security, Maven,  SpringSource STS, SVN, JSF/Icefaces


== Company GTInformatica / Senior Developer
From Oct. 2007 to  Oct. 2010.

=== Projects
* GT GuiaReporting, QEnergia, May. 2010
* GT/NetPlus, Feb. 2010 - Mar. 2010
* Outsourcing GT/ Promosoft, Nov. 2009 - Dec. 2009
* Outsourcing GT / Vigilarme, Oct. 2009
* OutSourcing GT/ RedCats LaRedoute, May 2008 – June 2009

.Table Title
|===
|Project | Description |Name of Column 3

|Cell in column 1, row 1
|Cell in column 2, row 1
|Cell in column 3, row 1

|Cell in column 1, row 2
|Cell in column 2, row 2
|Cell in column 3, row 2
|===

=== Description
* Did 1
* Did 2
* Did 3

=== Technologies
Grails, H2 Database, BIRT, jQuery, SpringSource STS, SVN, Spring, MySQL, BIRT,Hibernate, Log4j, Maven

////
== Company XPTO / Position Y
From May 2014 to May 2015.

=== Projects
* P1
* P1


=== Description
* Did 1
* Did 2
* Did 3

=== Technologies
X, Y, Z
////
